//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Actemium.WiSSWizard.Support {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ToolTipText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ToolTipText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Actemium.WiSSWizard.Support.ToolTipText", typeof(ToolTipText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controle van accountaanmeldingsgebeurtenissen:
        ///
        ///Met deze beveiligingsinstelling bepaalt u of elke aanmelding of afmelding van een gebruiker 
        ///vanaf een andere computer moet worden gecontroleerd, waarbij die computer wordt gebruikt 
        ///om de account te valideren. 
        ///Accountaanmeldingsgebeurtenissen worden gegenereerd als een domeingebruikersaccount wordt geverifieerd op een domeincontroller.
        ///
        ///De gebeurtenis wordt geregistreerd in het beveiligingslogboek van de domeincontroller. 
        ///Aanmeldingsgebeurtenissen w [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ttAuditAccountLogon {
            get {
                return ResourceManager.GetString("ttAuditAccountLogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controle van accountbeheer:
        ///
        ///Met deze beveiligingsinstelling bepaalt u of elke accountbeheergebeurtenis op een computer moet worden gecontroleerd. 
        ///Voorbeelden van accountbeheergebeurtenissen zijn:
        ///	- Er wordt een gebruikersaccount of gebruikersgroep gemaakt, gewijzigd of verwijderd.
        ///	- De naam van een gebruikersaccount wordt gewijzigd, of de account wordt uit- of ingeschakeld.
        ///	- Er wordt een wachtwoord ingesteld of gewijzigd.
        ///Als u deze beleidsinstelling definieert, kunt u opgeven of u geslaagde po [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ttAuditAccountManagement {
            get {
                return ResourceManager.GetString("ttAuditAccountManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controle van active Directory-toegang:  
        ///
        ///Met deze beveiligingsinstelling bepaalt u of er een controle moet worden uitgevoerd wanneer een
        ///gebruiker toegang probeert te krijgen tot een Active Directory-object waarvoor een afzonderlijke SACL
        ///(System Access Control List, systeemtoegangsbeheerlijst) is gedefinieerd.
        ///Deze waarde wordt standaard ingesteld in het groepsbeleidsobject Standaarddomeincontroller, en wordt
        ///niet gedefinieerd voor werkstations en servers omdat deze waarde dan geen betekenis heeft.        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ttAuditActiveDirectoryAcces {
            get {
                return ResourceManager.GetString("ttAuditActiveDirectoryAcces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controle van aanmeldingsgebeurtenissen:
        ///
        ///Met deze beveiligingsinstelling bepaalt u of er een controle moet worden 
        ///uitgevoerd wanneer een gebruiker zich aanmeldt of afmeldt bij een computer.
        ///
        ///Voorkeurs instelling: Geslaagde, mislukte.
        /// </summary>
        internal static string ttAuditLogonEvents {
            get {
                return ResourceManager.GetString("ttAuditLogonEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controle van objecttoegang:  
        ///
        ///Met deze beveiligingsinstelling bepaalt u of er een controle moet worden uitgevoerd wanneer een
        ///gebruiker toegang probeert te krijgen tot een object (bijvoorbeeld een bestand, map, registersleutel,
        ///printer, enzovoort) waarvoor een afzonderlijke SACL (System Access Control List, 
        ///systeemtoegangsbeheerlijst) is gedefinieerd.
        ///Als u deze beleidsinstelling definieert, kunt u opgeven of u geslaagde pogingen of mislukte pogingen wilt
        ///controleren of het type gebeurtenis helemaa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ttAuditObjectAcces {
            get {
                return ResourceManager.GetString("ttAuditObjectAcces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controle van beleidswijzigingen: 
        ///
        ///Met deze beveiligingsinstelling bepaalt u of er een controle moet worden uitgevoerd bij een wijziging van
        ///het beleid voor het toewijzen van gebruikersrechten, het controlebeleid of het beleid voor
        ///vertrouwensinstellingen.
        ///Als u deze beleidsinstelling definieert, kunt u opgeven of u geslaagde pogingen of mislukte pogingen wilt
        ///controleren of het type gebeurtenis helemaal niet wilt controleren. Als u geslaagde pogingen controleert,
        ///wordt er een vermelding gegenereerd  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ttAuditPolicyChange {
            get {
                return ResourceManager.GetString("ttAuditPolicyChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controle van gebruik van bevoegdheden:   
        ///
        ///Met deze beveiligingsinstelling bepaalt u of er een controle moet worden
        ///uitgevoerd wanneer gebruik wordt gemaakt van een gebruikersrecht.
        ///
        ///Voorkeursinstelling:     Geen controle.
        /// </summary>
        internal static string ttAuditPrivilegeUse {
            get {
                return ResourceManager.GetString("ttAuditPrivilegeUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controle van procesopsporing:   
        ///
        ///Met deze beveiligingsinstelling bepaalt u of u uitgebreide traceringsinformatie wilt controleren voor
        ///gebeurtenissen als het activeren van programma&apos;s, het afsluiten van processen, het uitvoeren van
        ///kopieerbewerkingen of de toegang tot indirecte objecten.
        ///Als u deze beleidsinstelling definieert, kunt u opgeven of u geslaagde pogingen of mislukte pogingen wilt
        ///controleren of het type gebeurtenis helemaal niet wilt controleren. Als u geslaagde pogingen controleert,
        ///wor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ttAuditProcessTracking {
            get {
                return ResourceManager.GetString("ttAuditProcessTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controle van systeemgebeurtenissen:   
        ///
        ///Met deze beveiligingsinstelling bepaalt u of er een controle moet worden uitgevoerd wanneer een
        ///gebruiker de computer afsluit of opnieuw start of als zich een gebeurtenis voordoet die van invloed is op
        ///de systeembeveiliging of het beveiligingslogboek.
        ///Als u deze beleidsinstelling definieert, kunt u opgeven of u geslaagde pogingen of mislukte pogingen wilt
        ///controleren of het type gebeurtenis helemaal niet wilt controleren. Als u geslaagde pogingen controleert,
        ///w [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ttAuditSytemEvents {
            get {
                return ResourceManager.GetString("ttAuditSytemEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoplay instellingen:
        ///
        ///Autoplay zorgt er voor dat op het moment dat er media in een drive wordt gekoppeld, dit direct wordt uitgevoerd. 
        ///Het is mogelijk dit uit te schakelen voor alle drives, of CD-ROM and removable media drives.
        ///
        ///Voorkeurs instelling: Uitschakelen voor ‘All drives’.
        /// </summary>
        internal static string ttAutoPlay {
            get {
                return ResourceManager.GetString("ttAutoPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically search for network folders and printers:
        ///
        ///Hiermee geeft u op dat periodiek wordt gezocht naar gedeelde mappen en printers in het netwerk.
        ///Alle gedeelde mappen en printers die worden gevonden, worden weergegeven in mijn netwerklocaties.
        ///
        ///Voorkeursinstelling: Uit.
        /// </summary>
        internal static string ttAutoSearchFoldersPrinters {
            get {
                return ResourceManager.GetString("ttAutoSearchFoldersPrinters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoorden opslaan in logboek:
        ///
        ///De opgegeven wachtwoorden worden leesbaar opgeslagen in het logboek. 
        ///Random gekozen wachtwoorden worden in het het invulveld leesbaar getoond indien er is gekozen om 
        ///het wachtwoord niet op te slaan in het logboek..
        /// </summary>
        internal static string ttChangeDefaultAccountsSavePasswordInLogFile {
            get {
                return ResourceManager.GetString("ttChangeDefaultAccountsSavePasswordInLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genereert een rapport met de huidige security 
        ///instellingen van dit systeem..
        /// </summary>
        internal static string ttCheckCurrentSettings {
            get {
                return ResourceManager.GetString("ttCheckCurrentSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display the contents of system folders: 
        ///
        ///Hiermee wordt de inhoud van systeemmappen weergegeven. Systeemmappen, zoals het systeemstation
        ///(meestal station C, tenzij u meer dan één station hebt op de computer), Program Files, Documents and
        ///Settings en Windows, bevatten bestanden die de computer nodig heeft om 
        ///goed te functioneren. De inhoud van deze mappen wordt standaard verborgen.
        ///
        ///Voorkeursinstelling: Aan.
        /// </summary>
        internal static string ttDisplayContentsSysFolders {
            get {
                return ResourceManager.GetString("ttDisplayContentsSysFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display the full path in the address bar:
        ///
        ///Hiermee wordt het volledige pad van het geopende bestand of de geopende
        ///map in de adresbalk van het venster weergegeven.
        ///
        ///Voorkeursinstelling: Aan.
        /// </summary>
        internal static string ttDisplayFullPathAddressBar {
            get {
                return ResourceManager.GetString("ttDisplayFullPathAddressBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windowsfirewall:
        ///
        ///Op deze Wizard pagina kunt u uitzonderingen in de firewall aangeven.
        ///Geeft u hier niets aan, dan wordt de firewall volledig dicht gezet.
        ///Een aantal opties is al weergegeven, overige applicaties welke toegang door de firewall nodig hebben
        ///kunnen worden opgezocht, daarnaast kunnen specifieke poorten worden opengezet..
        /// </summary>
        internal static string ttFireWall {
            get {
                return ResourceManager.GetString("ttFireWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide extensions for known file types:
        ///
        ///Hiermee wordt het laatste deel van een bestandsnaam verborgen, zodat 
        ///mapvensters overzichtelijker worden.
        ///
        ///Voorkeursinstelling: Uit.
        /// </summary>
        internal static string ttHideExtensions {
            get {
                return ResourceManager.GetString("ttHideExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide protected operating system files 
        ///
        ///Hiermee worden besturingssysteembestanden niet weergegeven in de lijst
        ///met bestanden in deze map, zodat ze niet per ongeluk kunnen worden verwijderd of gewijzigd.
        ///
        ///Voorkeursinstelling: Uit.
        /// </summary>
        internal static string ttHideProtectedSysFiles {
            get {
                return ResourceManager.GetString("ttHideProtectedSysFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MBSA:
        ///
        ///Microsoft Baseline Security Analyzer controleert de beveiliging van het systeem. 
        ///Dit kan alleen als MBSA is geïnstalleerd op het systeem. De controle neemt een aantal minuten in beslag.
        ///Het resultaat van deze analyzer wordt toegevoegd aan het logboek en kan worden gebruikt om
        ///additionele maatregelen te nemen. 
        ///Tevens kan het resultaat worden gebruikt om deze security checklist applicatie te verbeteren..
        /// </summary>
        internal static string ttMBSA {
            get {
                return ResourceManager.GetString("ttMBSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoord complexiteit betekent:
        ///
        ///- Wachtwoorden kunnen niet bestaan uit de gedeeltelijke of volledige naam van het gebruikersaccount
        ///- Een wachtwoord moet drie van de volgende vier typen tekens bevatten:
        ///	- Hoofdletters (A - Z)
        ///	- Kleine letters (a - z)
        ///	- Cijfers (0 – 9)
        ///	- Niet-alfanumerieke tekens (~!@#$%^&amp;*_-+=`|\(){}[]:;&quot;&apos;&lt;&gt;,.?/)
        ///
        ///Voorkeurs instelling: Ingeschakeld.
        /// </summary>
        internal static string ttPasswordComplexity {
            get {
                return ResourceManager.GetString("ttPasswordComplexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoorden opslaan met omkeerbare encryptie:
        ///
        ///Met deze beveiligingsinstelling wordt bepaald of wachtwoorden in het besturingssysteem moeten worden
        ///opgeslagen met omkeerbare encryptie.
        ///Het opslaan van wachtwoorden met omkeerbare codering is in feite hetzelfde als het opslaan van
        ///wachtwoorden in gewone tekst. 
        ///
        ///Voorkeurs instelling: Uitgeschakeld.
        /// </summary>
        internal static string ttPasswordEncryption {
            get {
                return ResourceManager.GetString("ttPasswordEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember each folder view settings 
        ///
        ///Hiermee blijven de afzonderlijke mapinstellingen behouden wanneer u een map sluit en vervolgens weer opent. 
        ///Wanneer deze optie niet is ingeschakeld, worden alle standaardinstellingen voor een map hersteld wanneer u de map sluit en opnieuw opent.
        ///
        ///Voorkeursinstelling: Uit.
        /// </summary>
        internal static string ttRembemberViewSettings {
            get {
                return ResourceManager.GetString("ttRembemberViewSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecteer externe gebruikers voor remotedesktop:
        ///
        ///Selecteer hier de lokale gebruikers die gebruik mogen van remote desktop vanaf dit systeem. 
        ///Gebruikers worden toegevoegd aan de gebruikersgroep “Remote Desktop” of “Externe bureabladgebruikers”.
        /// </summary>
        internal static string ttRemoteDesktopAddUsers {
            get {
                return ResourceManager.GetString("ttRemoteDesktopAddUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoorden opslaan in logboek:
        ///
        ///De opgegeven wachtwoorden worden leesbaar opgeslagen in het logboek. 
        ///Random gekozen wachtwoorden worden in het het invulveld leesbaar getoond indien er is gekozen om 
        ///het wachtwoord niet op te slaan in het logboek..
        /// </summary>
        internal static string ttSavePasswordInLogFile {
            get {
                return ResourceManager.GetString("ttSavePasswordInLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show hidden files and folders:
        ///
        ///Hiermee worden verborgen bestanden weergegeven in de lijst met bestanden in Windows Verkenner.
        ///
        ///Voorkeursinstelling: Aan.
        /// </summary>
        internal static string ttShowHiddenFolders {
            get {
                return ResourceManager.GetString("ttShowHiddenFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show encrypted or compressed NTFS files in color
        ///
        ///Hiermee worden de namen van de bestanden die u comprimeert of codeert op NTFS-stations,
        ///weergegeven in kleur wanneer u de bestanden weergeeft in een mapvenster. 
        ///Dit is niet van toepassing op mappen die u comprimeert met hulpprogramma’s voor ZIP-compressie.
        ///
        ///Voorkeursinstelling: Aan.
        /// </summary>
        internal static string ttShowNTFSinBlue {
            get {
                return ResourceManager.GetString("ttShowNTFSinBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geef reden bij afsluiten (shutdown event tracker):
        ///
        ///Bij het afsluiten of herstarten van het systeem dient een reden voor deze actie te worden opgegeven.
        ///(deze functionaliteit is niet beschikbaar voor Windows XP 32 bit systemen)
        ///
        ///Voorkeursinstelling: Uit.
        /// </summary>
        internal static string ttShutdownEventTracker {
            get {
                return ResourceManager.GetString("ttShutdownEventTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wat is UDP TCP:
        ///
        ///TCP: Transmission Control Protocol heeft als kenmerken dat het gegevens in een stream  kan versturen,
        ///waarbij de garantie wordt geleverd dat de 
        ///gegevens aankomen zoals ze verstuurd werden, en eventuele communicatiefouten, zowel in de gegevens 
        ///zelf als in de volgorde van de gegevens kunnen worden opgevangen.
        ///
        ///UDP: User Datagram Proctol  is minder betrouwbaar dan TCP, maar door een
        ///lagere overhead wel sneller. UDP biedt geen garantie dat de gegevens werkelijk aankomen.
        ///
        ///http://en. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TTtcpUdp {
            get {
                return ResourceManager.GetString("TTtcpUdp", resourceCulture);
            }
        }
    }
}
